### ISSUE TITLE
install script for GKE should create k8s cluster

### ISSUE THREAD

**Issue by amsaha** [CiscoAI/kubeflow-workflows#3]
currently the install_gke.bash script expects that the k8s cluster is already setup and the underlying kubectl is configured to access that cluster. We need to allow for:
1. k8s cluster to be created from within the script. Additionally, the k8s cluster name can be specified in the command line if a cluster is already created.
2. kubectl should be configured to access the specified/created k8s cluster using:
gcloud container clusters get-credentials <cluster-name> --zone <zone-name> --project <project-name>
    - both zone-name and cluster-name should be allowed to be specified via command line
    - project-name should be specified but the script should expect the project to already exist (since projects have billing associated, we should not create it as part of the installation script).

**Comment by ramdootp** [comment]
code checked in
