### ISSUE TITLE
Merge local-demo branch to main.

### ISSUE THREAD

**Issue by amsaha** [CiscoAI/kubeflow-workflows#43]
@xyhuang  made some changes to scripts to make the demo work on UCS on-prem setup. We need to combine.

**Comment by amsaha** [comment]
The tf-mnist/demo directory should probable be renamed "tf-mnist/ucs"? Also, could we have a description of the setup in tf-mnist/demo/readme?

**Comment by amsaha** [comment]
We can merge it only after we have updated our nightly to run tests on UCS setup as well. That means we first need a UCS setup :-)

**Comment by ramdootp** [comment]
image needs to be set to gpu based tf image. The existing bash scripts should do the rest.
Needs a gpu based dockerfile and an image needs to be posted to docker/gcr.

**Comment by ramdootp** [comment]
merged
