### ISSUE TITLE
serving pod error "FileSystemStoragePathSource encountered a file-system access error: Could not find base path /mnt/export for servable mnist"

### ISSUE THREAD

**Issue by jhua18** [CiscoAI/kubeflow-workflows#48]
I just pull the latest code base, and started re-running everything. Everything else seems to work as normal ( no exception at least), but I noticed a problem when trying to call serving service using the python client with connection rejection issue. Then I investigated a bit and found the following error in serving pod log:
`
kubectl logs mnist-v1-9b666f59c-gbzvt
Error from server (NotFound): pods "mnist-v1-9b666f59c-gbzvt" not found
jhua-mac:tf-mnist joshua.hua$ kubectl -n kubeflow logs mnist-v1-9b666f59c-gbzvt
2018-08-14 17:49:18.009986: I tensorflow_serving/model_servers/main.cc:154] Building single TensorFlow model file config:  model_name: mnist model_base_path: /mnt/export
2018-08-14 17:49:18.015699: I tensorflow_serving/model_servers/server_core.cc:444] Adding/updating models.
2018-08-14 17:49:18.015772: I tensorflow_serving/model_servers/server_core.cc:499]  (Re-)adding model: mnist
2018-08-14 17:49:18.016628: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:370] FileSystemStoragePathSource encountered a file-system access error: Could not find base path /mnt/export for servable mnist
...
`
Anyone seeing the same error? And fixes?

Thanks,

--Joshua

**Comment by jhua18** [comment]
And the log of nfs server pod is attached below:
`
kubectl -n kubeflow logs nfs-server-66f98986f5-jss6b
Serving /exports
Serving /
rpcinfo: can't contact rpcbind: : RPC: Unable to receive; errno = Connection refused
Starting rpcbind
exportfs: / does not support NFS export
NFS started
`
It might be one of the leads to the cause

**Comment by jhua18** [comment]
`
# the folder "/mnt" on nfs server is empty
kubectl -n kubeflow exec -it nfs-server-66f98986f5-6z24m  ls /mnt

## and the other folder "/exports" does have some seem to be trained model data
kubectl -n kubeflow exec -it nfs-server-66f98986f5-6z24m  ls /exports
data  index.html  model

kubectl -n kubeflow exec -it nfs-server-66f98986f5-6z24m  ls /exports/data
t10k-images-idx3-ubyte.gz  train-images-idx3-ubyte.gz
t10k-labels-idx1-ubyte.gz  train-labels-idx1-ubyte.gz

kubectl -n kubeflow exec -it nfs-server-66f98986f5-6z24m  ls /exports/model
events.out.tfevents.1534478424.tf-mnistjob-master-yhl9-0-wjqd1

`

**Comment by ramdootp** [comment]
AFAIK /exports is the correct location for data and model on nfs-server and /mnt is the mount path for the client. Are you seeing this issue consistently, even if you restart the setup again

**Comment by jhua18** [comment]
I have been trying many times after git pull early this week, and seeing the blocking issue consistently. I tried several ways, cleanup script, remove mnist folder, no luck
Can someone shed some lights?

**Comment by Akado2009** [comment]
@jhua18 
Hi! Had the same issue yesterday, cleared all the namespaces and restarted kubernetes cluster and now it is solved.

**Comment by jhua18** [comment]
@Akado2009 thanks for the confirmation! 

I just tried the same steps that did not work in past few days:
- pulled git again (no code change in repo this time).
- then re-ran cleanup.bash, and 'rm -rf mnist'. 
- ran from beginning:  install.bash, ..
- and finally, the results came out as expected.

Is there something in the files from artifcatory or images cause the problem?

**Comment by ramdootp** [comment]
so, is this a non-issue?

**Comment by Akado2009** [comment]
@ramdootp I believe it's is not an issue now.

**Comment by jhua18** [comment]
More updates: the problem can be reproduced after minikube stop/start. the new pod instance seems not having the mounted volume/folder of model

**Comment by amsaha** [comment]
@ramdootp have we tested on minikube at all? I thought this was entirely GKE based.

**Comment by ramdootp** [comment]
Yes. This is entirely gke based

**Comment by amsaha** [comment]
Closing this since we are not going to be supporting minikube.
